name: SCONE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - contourpy=1.0.5
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - cupti=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=7.0.6
  - jupyter_core=5.3.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libopenblas=0.2.20
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvmlite=0.36.0
  - lz4-c=1.9.4
  - magma=2.7.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.89.1
  - numba=0.53.1
  - numexpr=2.8.4
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1u
  - packaging=23.1
  - pandas=1.4.4
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=3.5.3
  - ply=3.11
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.1
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=19.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scipy=1.6.2
  - seaborn=0.12.2
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2020.3
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - click==8.1.3
    - docker-pycreds==0.4.0
    - faiss-gpu==1.7.2
    - gitdb==4.0.10
    - gitpython==3.1.31
    - joblib==1.2.0
    - matplotlib==3.7.2
    - pathtools==0.1.2
    - protobuf==4.23.3
    - scikit-learn==1.2.2
    - sentry-sdk==1.26.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - urllib3==1.26.16
    - wandb==0.15.4
